"use strict";

const identityErrorCodes = {
    REQUIREMENT_ID_INVALID_INPUT: "REQUIREMENT_ID_INVALID_INPUT",
    REQUIREMENT_ID_VALIDATION_FAILED: "REQUIREMENT_ID_VALIDATION_FAILED",
    REQUIREMENT_ID_UNSUPPORTED_VALUE: "REQUIREMENT_ID_UNSUPPORTED_VALUE",
    REQUIREMENT_ID_COLLISION: "REQUIREMENT_ID_COLLISION",
    REQUIREMENT_ID_INTERNAL_ERROR: "REQUIREMENT_ID_INTERNAL_ERROR"
};

module.exports = {
    identityErrorCodes
};
