// ─────────────────────────────────────────────────────────────────────────────
// GENERATION PLANNER
// Analyzes projectSpec and produces a deterministic generation plan:
//   - scaffold adapter selection using stack profiles
//   - strategy (DIRECT | SCAFFOLD_AI | CHUNKED | PARALLEL)
//   - token budgets
//   - generation units with dependency ordering
//   - repair policy
// ─────────────────────────────────────────────────────────────────────────────

const { detectProfile } = require("./stackProfiles");

const planGeneration = (projectSpec) => {
    const profile = detectProfile(projectSpec);
    const scaffoldAdapter = profile.name;
    const isMern = scaffoldAdapter === "mern";

    let scaffoldCoverage = 0.0;
    if (scaffoldAdapter === "mern") scaffoldCoverage = 0.85;
    else if (scaffoldAdapter === "react-vite") scaffoldCoverage = 0.8;
    else if (scaffoldAdapter === "nextjs") scaffoldCoverage = 0.7;
    else if (scaffoldAdapter === "express") scaffoldCoverage = 0.7;
    else if (scaffoldAdapter === "fastapi") scaffoldCoverage = 0.6;
    else scaffoldCoverage = 0.0; // vanilla/fallback

    const pagesCount = projectSpec.pagesAndRoutes?.length || 0;
    const compsCount = projectSpec.components?.length || 0;
    const apisCount = projectSpec.backendApis?.length || 0;
    const modelsCount = projectSpec.databaseModels?.length || 0;

    // Heuristics for estimated file output count
    const baseFiles = (scaffoldAdapter && scaffoldAdapter !== "vanilla") ? 4 : 2;
    const customFiles = pagesCount + compsCount + modelsCount + (apisCount > 0 ? 1 : 0);
    const totalFilesEstimate = baseFiles + customFiles;

    // Estimate output tokens
    const estimatedOutputTokens = (customFiles * 300) + (baseFiles * 200);

    // Complexity mapping
    let complexity = "low";
    if (customFiles > 5 || (projectSpec.integrations?.length || 0) > 0) {
        complexity = "moderate";
    }
    if (customFiles > 14 || estimatedOutputTokens > 5000 || isMern) {
        complexity = "high";
    }

    // Coupling analysis
    let dependencyCoupling = "low";
    if (
        (projectSpec.backend && projectSpec.backend !== "None" &&
         projectSpec.frontend && projectSpec.frontend !== "None") ||
        modelsCount > 0 || isMern
    ) {
        dependencyCoupling = "high";
    }

    // Deterministic infrastructure files generated by the stack profile
    const scaffoldFiles = profile.getScaffoldFiles(projectSpec);
    const deterministicFiles = scaffoldFiles.map(f => f.name);

    // ── STRATEGY SELECTION ────────────────────────────────────────────────────
    let strategy = "DIRECT";
    let tokenBudget = 3000;

    if (isMern) {
        // MERN full-stack ALWAYS uses CHUNKED — too complex for single call
        strategy = "CHUNKED";
        tokenBudget = 4000; // per-unit budget
    } else if (scaffoldCoverage > 0.5) {
        strategy = "SCAFFOLD_AI";
        if (complexity === "high" && estimatedOutputTokens > 5000) {
            if (dependencyCoupling === "low" && (compsCount + pagesCount) >= 2) {
                strategy = "PARALLEL";
            } else {
                strategy = "CHUNKED";
            }
        }
    } else {
        strategy = "DIRECT";
        if (complexity === "high" && estimatedOutputTokens > 5000) {
            if (dependencyCoupling === "low") {
                strategy = "PARALLEL";
            } else {
                strategy = "CHUNKED";
            }
        }
    }

    // Token budget calculation
    if (strategy === "DIRECT" || strategy === "SCAFFOLD_AI") {
        tokenBudget = Math.min(Math.max(Math.floor(estimatedOutputTokens * 1.8), 3000), 8000);
    } else {
        tokenBudget = isMern ? 4000 : 2500; // per-unit budget
    }

    // ── GENERATION UNITS ─────────────────────────────────────────────────────
    const generationUnits = [];

    if (isMern) {
        // MERN-specific dependency-ordered generation units
        // Unit 1: Backend foundation — models + DB config
        generationUnits.push({
            id: "backend_foundation",
            description: "Generate backend database models (Mongoose schemas), database configuration, authentication middleware, error middleware, and JWT utility. These are foundational — all other backend files depend on them.",
            type: "backend-foundation",
            dependencies: [],
            estimatedTokens: 3500,
            meta: {
                models: projectSpec.databaseModels || [],
                environmentVariables: projectSpec.environmentVariables || [],
                authentication: projectSpec.authentication || "None"
            }
        });

        // Unit 2: Backend services — controllers + routes
        const modelNames = (projectSpec.databaseModels || []).map(m => m.name).join(", ");
        generationUnits.push({
            id: "backend_api",
            description: "Generate backend Express controllers, API route handlers, and app.js/server.js entry files. All REST endpoints including auth (register/login) if needed, and CRUD controllers/routes for: " + (modelNames || "database resources") + ".",
            type: "backend-api",
            dependencies: ["backend_foundation"],
            estimatedTokens: 4000,
            meta: {
                apis: projectSpec.backendApis || [],
                models: projectSpec.databaseModels || [],
                authentication: projectSpec.authentication || "None"
            }
        });

        // Unit 3: Frontend app shell + auth
        generationUnits.push({
            id: "frontend_shell",
            description: "Generate frontend React app shell: main.jsx entry point, App.jsx with React Router routes, AuthContext, useAuth hook, and API service layer (api.js, authService.js, and model-specific services). Include index.css with Tailwind directives and global styles.",
            type: "frontend-shell",
            dependencies: ["backend_foundation"],
            estimatedTokens: 3500,
            meta: {
                pages: projectSpec.pagesAndRoutes || [],
                authentication: projectSpec.authentication || "None",
                models: projectSpec.databaseModels || []
            }
        });

        // Unit 4: Frontend pages
        const pageNames = (projectSpec.pagesAndRoutes || []).map(p => p.name).join(", ");
        generationUnits.push({
            id: "frontend_pages",
            description: "Generate all frontend React page components: " + (pageNames || "requested views") + ". Each page must import and use required components.",
            type: "frontend-pages",
            dependencies: ["frontend_shell"],
            estimatedTokens: 4000,
            meta: {
                pages: projectSpec.pagesAndRoutes || [],
                components: projectSpec.components || []
            }
        });

        // Unit 5: Frontend components
        const componentNames = (projectSpec.components || []).map(c => c.name).join(", ");
        generationUnits.push({
            id: "frontend_components",
            description: "Generate all frontend React reusable components: " + (componentNames || "requested design components") + ". All components must be visually professional with Tailwind CSS.",
            type: "frontend-components",
            dependencies: ["frontend_shell"],
            estimatedTokens: 4000,
            meta: {
                components: projectSpec.components || []
            }
        });

        // Unit 6: Documentation
        generationUnits.push({
            id: "documentation",
            description: "Generate the root README.md with complete project overview, setup instructions, API documentation, environment variable guide, and deployment guide. Also generate root .env or any missing config files.",
            type: "documentation",
            dependencies: ["backend_api", "frontend_pages", "frontend_components"],
            estimatedTokens: 2000,
            meta: {
                apis: projectSpec.backendApis || [],
                environmentVariables: projectSpec.environmentVariables || []
            }
        });

    } else if (strategy === "DIRECT" || strategy === "SCAFFOLD_AI") {
        // Single consolidated source generation unit
        generationUnits.push({
            id: "all_source_files",
            description: "Generate all project custom implementation source files consolidated in one call",
            dependencies: [],
            estimatedTokens: estimatedOutputTokens
        });
    } else {
        // Non-MERN Chunked/Parallel — multi-call units
        generationUnits.push({
            id: "core_entry",
            description: "Generate core entry files and setup main configurations",
            dependencies: []
        });

        if (projectSpec.databaseModels && projectSpec.databaseModels.length > 0) {
            generationUnits.push({
                id: "db_models",
                description: "Generate database schemas and models",
                type: "models",
                dependencies: []
            });
        }

        if (projectSpec.pagesAndRoutes) {
            projectSpec.pagesAndRoutes.forEach(page => {
                generationUnits.push({
                    id: `page_${page.name.replace(/\s+/g, "")}`,
                    description: `Generate page: ${page.name}`,
                    type: "page",
                    meta: page,
                    dependencies: ["core_entry"]
                });
            });
        }

        if (projectSpec.components) {
            projectSpec.components.forEach(comp => {
                generationUnits.push({
                    id: `component_${comp.name.replace(/\s+/g, "")}`,
                    description: `Generate component: ${comp.name}`,
                    type: "component",
                    meta: comp,
                    dependencies: ["core_entry"]
                });
            });
        }
    }

    // ── PARALLEL GROUPS ───────────────────────────────────────────────────────
    // Group units by their dependency wave for parallel execution
    const parallelGroups = [];
    const visited = new Set();
    let remaining = [...generationUnits];

    while (remaining.length > 0) {
        const group = remaining.filter(u => u.dependencies.every(d => visited.has(d)));
        if (group.length === 0) {
            // Circular dependency fallback — push remaining as final group
            parallelGroups.push(remaining);
            break;
        }
        parallelGroups.push(group);
        group.forEach(u => visited.add(u.id));
        remaining = remaining.filter(u => !visited.has(u.id));
    }

    return {
        strategy,
        complexity,
        estimatedOutputSize: estimatedOutputTokens,
        scaffoldAdapter,
        deterministicFiles,
        generationUnits,
        parallelGroups,
        validationProfile: scaffoldAdapter,
        tokenBudget,
        isMern: isMern,
        repairPolicy: {
            maxAttempts: 2
        }
    };
};

module.exports = { planGeneration };
