"use strict";

const rtmErrorCodes = {
    RTM_INVALID_INPUT: "RTM_INVALID_INPUT",
    RTM_INVALID_REQUIREMENT: "RTM_INVALID_REQUIREMENT",
    RTM_DUPLICATE_REQUIREMENT: "RTM_DUPLICATE_REQUIREMENT",
    RTM_INTERNAL_ERROR: "RTM_INTERNAL_ERROR",
    RTM_INVALID_STRUCTURE: "RTM_INVALID_STRUCTURE",
    RTM_INVALID_ENTRY: "RTM_INVALID_ENTRY",
    RTM_DUPLICATE_STABLE_ID: "RTM_DUPLICATE_STABLE_ID",
    RTM_DUPLICATE_DISPLAY_ID: "RTM_DUPLICATE_DISPLAY_ID",
    RTM_INVALID_STATUS: "RTM_INVALID_STATUS",
    RTM_INVALID_CATEGORY: "RTM_INVALID_CATEGORY",
    RTM_INVALID_TAGS: "RTM_INVALID_TAGS"
};

module.exports = {
    rtmErrorCodes
};
