"use strict";

const checkpointErrorCodes = Object.freeze({
    CHECKPOINT_INVALID_INPUT: "CHECKPOINT_INVALID_INPUT",
    CHECKPOINT_INVALID_PLANNER: "CHECKPOINT_INVALID_PLANNER",
    CHECKPOINT_DUPLICATE_TASK: "CHECKPOINT_DUPLICATE_TASK",
    CHECKPOINT_INTERNAL_ERROR: "CHECKPOINT_INTERNAL_ERROR",
    RESUME_INVALID_INPUT: "RESUME_INVALID_INPUT",
    RESUME_INVALID_CHECKPOINT: "RESUME_INVALID_CHECKPOINT",
    RESUME_INTERNAL_ERROR: "RESUME_INTERNAL_ERROR",
    CHECKPOINT_INVALID_STRUCTURE: "CHECKPOINT_INVALID_STRUCTURE",
    CHECKPOINT_INVALID_METADATA: "CHECKPOINT_INVALID_METADATA",
    CHECKPOINT_INVALID_EXECUTION_STATE: "CHECKPOINT_INVALID_EXECUTION_STATE"
});

module.exports = {
    checkpointErrorCodes
};
