"use strict";

const checkpointErrorCodes = Object.freeze({
    CHECKPOINT_INVALID_INPUT: "CHECKPOINT_INVALID_INPUT",
    CHECKPOINT_INVALID_PLANNER: "CHECKPOINT_INVALID_PLANNER",
    CHECKPOINT_DUPLICATE_TASK: "CHECKPOINT_DUPLICATE_TASK",
    CHECKPOINT_INTERNAL_ERROR: "CHECKPOINT_INTERNAL_ERROR"
});

module.exports = {
    checkpointErrorCodes
};
