"use strict";

const checkpointStoreErrorCodes = Object.freeze({
    CHECKPOINT_STORE_NOT_IMPLEMENTED: "CHECKPOINT_STORE_NOT_IMPLEMENTED",
    CHECKPOINT_STORE_INVALID_ARGUMENT: "CHECKPOINT_STORE_INVALID_ARGUMENT",
    CHECKPOINT_STORE_OPERATION_FAILED: "CHECKPOINT_STORE_OPERATION_FAILED"
});

module.exports = {
    checkpointStoreErrorCodes
};
