"use strict";

const executionRuntimeAdapterErrorCodes = Object.freeze({
    EXECUTION_RUNTIME_INVALID_INPUT: "EXECUTION_RUNTIME_INVALID_INPUT",
    EXECUTION_RUNTIME_INVALID_REQUEST: "EXECUTION_RUNTIME_INVALID_REQUEST",
    EXECUTION_RUNTIME_UNSUPPORTED_MODE: "EXECUTION_RUNTIME_UNSUPPORTED_MODE",
    EXECUTION_RUNTIME_EXECUTION_FAILED: "EXECUTION_RUNTIME_EXECUTION_FAILED"
});

module.exports = {
    executionRuntimeAdapterErrorCodes
};
