"use strict";

const runtimeConfigErrorCodes = Object.freeze({
    RUNTIME_CONFIG_INVALID_INPUT: "RUNTIME_CONFIG_INVALID_INPUT",
    RUNTIME_CONFIG_INVALID_STRUCTURE: "RUNTIME_CONFIG_INVALID_STRUCTURE",
    RUNTIME_CONFIG_UNKNOWN_PROPERTY: "RUNTIME_CONFIG_UNKNOWN_PROPERTY",
    RUNTIME_CONFIG_INVALID_MODE: "RUNTIME_CONFIG_INVALID_MODE"
});

module.exports = {
    runtimeConfigErrorCodes
};
