"use strict";

const verificationRepairBridgeErrorCodes = Object.freeze({
    VERIFICATION_REPAIR_INVALID_INPUT: "VERIFICATION_REPAIR_INVALID_INPUT",
    VERIFICATION_REPAIR_VERIFICATION_FAILED: "VERIFICATION_REPAIR_VERIFICATION_FAILED",
    VERIFICATION_REPAIR_REPAIR_FAILED: "VERIFICATION_REPAIR_REPAIR_FAILED",
    VERIFICATION_REPAIR_BRIDGE_FAILED: "VERIFICATION_REPAIR_BRIDGE_FAILED"
});

module.exports = {
    verificationRepairBridgeErrorCodes
};
