"use strict";

const workerPoolErrorCodes = Object.freeze({
    WORKER_POOL_INVALID_INPUT: "WORKER_POOL_INVALID_INPUT",
    WORKER_POOL_INVALID_STATE: "WORKER_POOL_INVALID_STATE",
    WORKER_POOL_NO_AVAILABLE_WORKERS: "WORKER_POOL_NO_AVAILABLE_WORKERS",
    WORKER_POOL_DUPLICATE_WORKER: "WORKER_POOL_DUPLICATE_WORKER",
    WORKERPOOL_ALLOCATION_FAILED: "WORKERPOOL_ALLOCATION_FAILED",
    WORKER_POOL_ALLOCATION_FAILED: "WORKER_POOL_ALLOCATION_FAILED",
    WORKERPOOL_INVALID_STATE: "WORKERPOOL_INVALID_STATE",
    WORKERPOOL_RELEASE_FAILED: "WORKERPOOL_RELEASE_FAILED",
    WORKER_POOL_RELEASE_FAILED: "WORKER_POOL_RELEASE_FAILED",
    WORKERPOOL_EXECUTION_FAILED: "WORKERPOOL_EXECUTION_FAILED",
    WORKER_POOL_EXECUTION_FAILED: "WORKER_POOL_EXECUTION_FAILED"
});

module.exports = {
    workerPoolErrorCodes
};
