"use strict";

const workerPoolErrorCodes = Object.freeze({
    WORKER_POOL_INVALID_INPUT: "WORKER_POOL_INVALID_INPUT",
    WORKER_POOL_INVALID_STATE: "WORKER_POOL_INVALID_STATE",
    WORKER_POOL_NO_AVAILABLE_WORKERS: "WORKER_POOL_NO_AVAILABLE_WORKERS",
    WORKER_POOL_DUPLICATE_WORKER: "WORKER_POOL_DUPLICATE_WORKER"
});

module.exports = {
    workerPoolErrorCodes
};
