"use strict";

const taskGraphErrorCodes = {
    TASK_GRAPH_INVALID_INPUT: "TASK_GRAPH_INVALID_INPUT",
    TASK_GRAPH_INVALID_REQUIREMENT: "TASK_GRAPH_INVALID_REQUIREMENT",
    TASK_GRAPH_DUPLICATE_NODE: "TASK_GRAPH_DUPLICATE_NODE",
    TASK_GRAPH_INTERNAL_ERROR: "TASK_GRAPH_INTERNAL_ERROR"
};

module.exports = {
    taskGraphErrorCodes
};
