const errorCodes = {
    MISSING_VERSION: "MISSING_VERSION",
    INVALID_VERSION: "INVALID_VERSION",
    MISSING_REQUIRED: "MISSING_REQUIRED",
    INVALID_TYPE: "INVALID_TYPE",
    INVALID_VALUE: "INVALID_VALUE",
    DUPLICATE_ROUTE: "DUPLICATE_ROUTE",
    DUPLICATE_API: "DUPLICATE_API",
    DUPLICATE_COMPONENT: "DUPLICATE_COMPONENT",
    DUPLICATE_MODEL: "DUPLICATE_MODEL",
    INVALID_HTTP_METHOD: "INVALID_HTTP_METHOD",
    INVALID_API_PATH: "INVALID_API_PATH",
    INVALID_PAGE_ROUTE: "INVALID_PAGE_ROUTE",
    INVALID_ENV_VAR: "INVALID_ENV_VAR",
    INVALID_DEP_NAME: "INVALID_DEP_NAME",
    UNKNOWN_FIELD: "UNKNOWN_FIELD"
};

const createError = (code, path, message, keyword) => ({
    code,
    path,
    message,
    keyword
});

module.exports = {
    errorCodes,
    createError
};
