"use strict";

const classificationErrorCodes = {
    CLASSIFICATION_INVALID_INPUT: "CLASSIFICATION_INVALID_INPUT",
    CLASSIFICATION_VALIDATION_FAILED: "CLASSIFICATION_VALIDATION_FAILED",
    CLASSIFICATION_INTERNAL_ERROR: "CLASSIFICATION_INTERNAL_ERROR"
};

module.exports = {
    classificationErrorCodes
};
