"use strict";

const gatewayErrorCodes = Object.freeze({
    GATEWAY_PROVIDER_NOT_FOUND: "GATEWAY_PROVIDER_NOT_FOUND",
    GATEWAY_INVALID_REQUEST: "GATEWAY_INVALID_REQUEST",
    GATEWAY_DUPLICATE_PROVIDER: "GATEWAY_DUPLICATE_PROVIDER",
    GATEWAY_EXECUTION_FAILED: "GATEWAY_EXECUTION_FAILED",
    GATEWAY_NO_PROVIDER_AVAILABLE: "GATEWAY_NO_PROVIDER_AVAILABLE",
    GATEWAY_TIMEOUT: "GATEWAY_TIMEOUT",
    GATEWAY_ALL_PROVIDERS_FAILED: "GATEWAY_ALL_PROVIDERS_FAILED",
    GATEWAY_CAPABILITY_UNSUPPORTED: "GATEWAY_CAPABILITY_UNSUPPORTED"
});

module.exports = {
    gatewayErrorCodes
};
