"use strict";

const gatewayErrorCodes = Object.freeze({
    GATEWAY_PROVIDER_NOT_FOUND: "GATEWAY_PROVIDER_NOT_FOUND",
    GATEWAY_INVALID_REQUEST: "GATEWAY_INVALID_REQUEST",
    GATEWAY_DUPLICATE_PROVIDER: "GATEWAY_DUPLICATE_PROVIDER",
    GATEWAY_EXECUTION_FAILED: "GATEWAY_EXECUTION_FAILED"
});

module.exports = {
    gatewayErrorCodes
};
