"use strict";

const providerErrorCodes = Object.freeze({
    PROVIDER_INVALID_INPUT: "PROVIDER_INVALID_INPUT",
    PROVIDER_INVALID_STRUCTURE: "PROVIDER_INVALID_STRUCTURE",
    PROVIDER_DUPLICATE_CAPABILITY: "PROVIDER_DUPLICATE_CAPABILITY",
    PROVIDER_UNKNOWN_PROPERTY: "PROVIDER_UNKNOWN_PROPERTY"
});

module.exports = {
    providerErrorCodes
};
