"use strict";

const providerInterfaceErrorCodes = Object.freeze({
    PROVIDER_INTERFACE_NOT_IMPLEMENTED: "PROVIDER_INTERFACE_NOT_IMPLEMENTED",
    PROVIDER_INTERFACE_INVALID_ARGUMENT: "PROVIDER_INTERFACE_INVALID_ARGUMENT",
    PROVIDER_INTERFACE_UNSUPPORTED_OPERATION: "PROVIDER_INTERFACE_UNSUPPORTED_OPERATION"
});

module.exports = {
    providerInterfaceErrorCodes
};
