"use strict";

/**
 * Engineering certification error taxonomy (Phase 13E).
 */
const certificationErrorCodes = Object.freeze({
    INVALID_INPUT: "INVALID_INPUT",
    INVALID_AUDIT_RESULT: "INVALID_AUDIT_RESULT",
    INVALID_RELEASE_RESULT: "INVALID_RELEASE_RESULT",
    INVALID_READINESS_RESULT: "INVALID_READINESS_RESULT",
    INVALID_BENCHMARK_RESULT: "INVALID_BENCHMARK_RESULT",
    INVALID_CERTIFICATION_SCORE: "INVALID_CERTIFICATION_SCORE",
    CERTIFICATION_FAILED: "CERTIFICATION_FAILED",
    REPORT_BUILD_FAILED: "REPORT_BUILD_FAILED",
    INTERNAL_ERROR: "INTERNAL_ERROR"
});

module.exports = {
    certificationErrorCodes
};
