"use strict";

const contextErrorCodes = Object.freeze({
    CONTEXT_INVALID_INPUT: "CONTEXT_INVALID_INPUT",
    CONTEXT_INVALID_PROJECT_SPEC: "CONTEXT_INVALID_PROJECT_SPEC",
    CONTEXT_INVALID_REQUIREMENT: "CONTEXT_INVALID_REQUIREMENT",
    CONTEXT_INVALID_TASK: "CONTEXT_INVALID_TASK",
    CONTEXT_INVALID_REPOSITORY: "CONTEXT_INVALID_REPOSITORY",
    CONTEXT_TARGET_NOT_FOUND: "CONTEXT_TARGET_NOT_FOUND",
    CONTEXT_INVALID_IMPORT_METADATA: "CONTEXT_INVALID_IMPORT_METADATA",
    CONTEXT_INTERNAL_ERROR: "CONTEXT_INTERNAL_ERROR"
});

module.exports = {
    contextErrorCodes
};
