"use strict";

const verificationErrors = Object.freeze({
    VERIFICATION_SYNTAX_ERROR: "VERIFICATION_SYNTAX_ERROR",
    VERIFICATION_IMPORT_ERROR: "VERIFICATION_IMPORT_ERROR",
    VERIFICATION_DEPENDENCY_ERROR: "VERIFICATION_DEPENDENCY_ERROR",
    VERIFICATION_STRUCTURE_ERROR: "VERIFICATION_STRUCTURE_ERROR",
    VERIFICATION_PROFILE_ERROR: "VERIFICATION_PROFILE_ERROR",
    VERIFICATION_INTERNAL_ERROR: "VERIFICATION_INTERNAL_ERROR"
});

module.exports = {
    verificationErrors
};
