"use strict";

const executionErrorCodes = Object.freeze({
    EXECUTION_INVALID_INPUT: "EXECUTION_INVALID_INPUT",
    EXECUTION_INVALID_TASK_GRAPH: "EXECUTION_INVALID_TASK_GRAPH",
    EXECUTION_MUTABLE_INPUT: "EXECUTION_MUTABLE_INPUT",
    EXECUTION_DUPLICATE_TASK: "EXECUTION_DUPLICATE_TASK"
});

module.exports = {
    executionErrorCodes
};
