"use strict";

const recoveryErrorCodes = Object.freeze({
    RECOVERY_INVALID_INPUT: "RECOVERY_INVALID_INPUT",
    RECOVERY_INVALID_CHECKPOINT: "RECOVERY_INVALID_CHECKPOINT",
    RECOVERY_INVALID_PIPELINE: "RECOVERY_INVALID_PIPELINE",
    RECOVERY_UNSUPPORTED_FAILURE: "RECOVERY_UNSUPPORTED_FAILURE"
});

module.exports = {
    recoveryErrorCodes
};
