"use strict";

const schedulerErrorCodes = Object.freeze({
    SCHEDULER_INVALID_INPUT: "SCHEDULER_INVALID_INPUT",
    SCHEDULER_INVALID_STATE: "SCHEDULER_INVALID_STATE",
    SCHEDULER_INVALID_WORKER: "SCHEDULER_INVALID_WORKER",
    SCHEDULER_DEPENDENCY_ERROR: "SCHEDULER_DEPENDENCY_ERROR",
    SCHEDULER_INVALID_GRAPH: "SCHEDULER_INVALID_GRAPH",
    SCHEDULER_CIRCULAR_DEPENDENCY: "SCHEDULER_CIRCULAR_DEPENDENCY",
    SCHEDULER_INVALID_ORDER: "SCHEDULER_INVALID_ORDER",
    SCHEDULER_EXECUTION_FAILED: "SCHEDULER_EXECUTION_FAILED"
});

module.exports = {
    schedulerErrorCodes
};
