"use strict";

const schedulerErrorCodes = Object.freeze({
    SCHEDULER_INVALID_INPUT: "SCHEDULER_INVALID_INPUT",
    SCHEDULER_INVALID_STATE: "SCHEDULER_INVALID_STATE",
    SCHEDULER_INVALID_WORKER: "SCHEDULER_INVALID_WORKER",
    SCHEDULER_DEPENDENCY_ERROR: "SCHEDULER_DEPENDENCY_ERROR"
});

module.exports = {
    schedulerErrorCodes
};
