"use strict";

const vfsErrorCodes = Object.freeze({
    VFS_INVALID_INPUT: "VFS_INVALID_INPUT",
    VFS_INVALID_FILE: "VFS_INVALID_FILE",
    VFS_DUPLICATE_PATH: "VFS_DUPLICATE_PATH",
    VFS_TRANSACTION_ALREADY_ACTIVE: "VFS_TRANSACTION_ALREADY_ACTIVE",
    VFS_TRANSACTION_NOT_ACTIVE: "VFS_TRANSACTION_NOT_ACTIVE",
    VFS_TRANSACTION_INVALID_STATE: "VFS_TRANSACTION_INVALID_STATE",
    VFS_TRANSACTION_INTERNAL_ERROR: "VFS_TRANSACTION_INTERNAL_ERROR",
    VFS_FILE_ALREADY_EXISTS: "VFS_FILE_ALREADY_EXISTS",
    VFS_FILE_NOT_FOUND: "VFS_FILE_NOT_FOUND",
    VFS_TRANSACTION_REQUIRED: "VFS_TRANSACTION_REQUIRED",
    VFS_OPERATION_INTERNAL_ERROR: "VFS_OPERATION_INTERNAL_ERROR",
    VFS_INTERNAL_ERROR: "VFS_INTERNAL_ERROR"
});

module.exports = {
    vfsErrorCodes
};
